// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmylOvI2P8k_do6uydbA563Np2JjXmUDw',
    appId: '1:546467456849:web:d09d9e7cc483e7ee5bd570',
    messagingSenderId: '546467456849',
    projectId: 'collegecrush-eec15',
    authDomain: 'collegecrush-eec15.firebaseapp.com',
    storageBucket: 'collegecrush-eec15.firebasestorage.app',
    measurementId: 'G-10KPQWN4VC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKZk_NEi_6Ns0NKWHsYUOnPxzfaJuavO8',
    appId: '1:546467456849:android:a77d2c1e912f3fb75bd570',
    messagingSenderId: '546467456849',
    projectId: 'collegecrush-eec15',
    storageBucket: 'collegecrush-eec15.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVRWbk_ee9e0R_6hrY4MbSXIfE9VabOd8',
    appId: '1:546467456849:ios:324511e284006fc95bd570',
    messagingSenderId: '546467456849',
    projectId: 'collegecrush-eec15',
    storageBucket: 'collegecrush-eec15.firebasestorage.app',
    iosBundleId: 'com.example.campusCrush',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVRWbk_ee9e0R_6hrY4MbSXIfE9VabOd8',
    appId: '1:546467456849:ios:324511e284006fc95bd570',
    messagingSenderId: '546467456849',
    projectId: 'collegecrush-eec15',
    storageBucket: 'collegecrush-eec15.firebasestorage.app',
    iosBundleId: 'com.example.campusCrush',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCmylOvI2P8k_do6uydbA563Np2JjXmUDw',
    appId: '1:546467456849:web:76706be487b851925bd570',
    messagingSenderId: '546467456849',
    projectId: 'collegecrush-eec15',
    authDomain: 'collegecrush-eec15.firebaseapp.com',
    storageBucket: 'collegecrush-eec15.firebasestorage.app',
    measurementId: 'G-SHZNMBK8XR',
  );
}
